# Use the same base image as the app Dockerfile
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update \
    && apt-get install -y \
        pkg-config \
        libmariadb-dev \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /mysql_login

# Copy the requirements file and install dependencies
COPY app/requirements.txt /mysql_login/
RUN pip install --no-cache-dir -r requirements.txt

# Install test dependencies
RUN pip install --no-cache-dir pytest

# Copy the application and test code
COPY app/ /mysql_login/app/
COPY test/ /mysql_login/test/

# Run tests
CMD ["python", "-m", "unittest", "discover", "test"]
