# Use the same base image as the app Dockerfile
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set default environment variables for  testing the application
ENV MYSQL_HOST=localhost
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password
ENV MYSQL_DATABASE=database
ENV MYSQL_PORT=3306

# Install system dependencies
RUN apt-get update \
    && apt-get install -y \
        pkg-config \
        libmariadb-dev \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /mysql_login

# Copy the requirements file and install dependencies
COPY app/requirements.txt /mysql_login/
RUN pip install --no-cache-dir -r requirements.txt

# Install test dependencies
RUN pip install --no-cache-dir pytest pytest-html

# Copy the application and test code
COPY app/ /mysql_login/app/
COPY test/ /mysql_login/test/

# Default command to run tests and generate the requested report
CMD ["/bin/sh", "-c", "if [ \"$REPORT_TYPE\" = \"html\" ]; then pytest --html=report.html; cp report.html /report.html; else pytest --junitxml=report.xml; cp report.xml /report.xml; fi"]
